### ISSUE TITLE
Add some buttons for common actions

### ISSUE THREAD

**Issue by Hixie** [Hixie/cuddlyworld-ide#32] opened 2020-10-24 21:55 UTC
- [ ] creating a door location with its thresholds, door sides, etc.
- [ ] creating a room with a floor

**Comment by Hixie** [comment] 2020-10-30 06:46
I've landed the UI for this but the actual templates still need filling in

**Comment by treeplate** [comment] 2020-11-01 02:00
Duplicate of #53

**Closed as completed by treeplate** 2020-11-01 02:00 UTC
Labels: templates
